DeclareNounouGestNounouBundle_accueil:
    pattern:  /
    defaults: { _controller: DeclareNounouGestNounouBundle:GestNounou:index }
    requirements: { _method: get }

DeclareNounouGestNounouBundle_enfant:
    resource: "@DeclareNounouGestNounouBundle/Resources/config/routing/enfant.yml"
    prefix: /enfant

DeclareNounouGestNounouBundle_nounou:
    resource: "@DeclareNounouGestNounouBundle/Resources/config/routing/nounou.yml"
    prefix: /nounou

DeclareNounouGestNounouBundle_contrat:
    resource: "@DeclareNounouGestNounouBundle/Resources/config/routing/contrat.yml"
    prefix: /contrat

DeclareNounouGestNounouBundel_pointage:
    resource: "@DeclareNounouGestNounouBundle/Resources/config/routing/pointage.yml"
    prefix: /pointage
