language: php
php:
  - 5.3
  - 5.4
branches:
  only:
    - master
before_script: 
  - composer self-update
  - composer install --dev --prefer-source
  - mysql -e 'create database `declarenounoutest`;'
  - mysql declarenounoutest < src/DeclareNounou/GestNounouBundle/Tests/Resources/data/fixture.sql
  - mv src/DeclareNounou/GestNounouBundle/Tests/Functional/config/parameters.yml.dist src/DeclareNounou/GestNounouBundle/Tests/Functional/config/parameters.yml
script: phpunit -c app --coverage-text
