# importation des routes de NounouBundle
declare_nounou_gest_nounou:
    resource: "@DeclareNounouGestNounouBundle/Resources/config/routing.yml"
    prefix:   /

declare_nounou_user:
    resource: "@DeclareNounouUserBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    defaults: { _locale: fr }
    requirements:
        _locale: fr

# importation des routes de FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    defaults: { _locale: fr }
    requirements:
        _locale: fr

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    defaults: { _locale: fr }
    requirements:
        _locale: fr

fos_user_registrer:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    defaults: { _locale: fr }
    requirements:
        _locale: fr

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults: { _locale: fr }
    requirements:
        _locale: fr

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults: { _locale: fr }
    requirements:
        _locale: fr
