<?php

namespace DeclareNounou\GestNounouBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NounouRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NounouRepository extends EntityRepository
{
}
