<?php

namespace DeclareNounou\GestNounouBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PointageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageRepository extends EntityRepository
{
    public function findByContractAndMonth($contract, $date)
    {
        $selectedDate = new \DateTime($date);
        $dateBegin = $selectedDate->modify('first day of this month')->format('Y-m-d');
        $dateEnd = $selectedDate->modify('last day of this month')->format('Y-m-d');
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.contrat', 'c')
                ->where('c.id = :contract')
                ->andWhere('p.datePointage >= :begin')
                ->andWhere('p.datePointage <= :end')
                ->setParameter('contract', $contract)
                ->setParameter('begin', $dateBegin)
                ->setParameter('end', $dateEnd)
                ->orderBy('p.datePointage', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
