pointage:
    pattern:  /
    defaults: { _controller: "DeclareNounouGestNounouBundle:Pointage:index" }
    requirements: { _method: get }

pointage_show:
    pattern:  /{id}/show
    defaults: { _controller: "DeclareNounouGestNounouBundle:Pointage:show" }
    requirements: { _method: get }

pointage_new:
    pattern:  /new
    defaults: { _controller: "DeclareNounouGestNounouBundle:Pointage:new" }
    requirements: { _method: get }

pointage_create:
    pattern:  /create
    defaults: { _controller: "DeclareNounouGestNounouBundle:Pointage:create" }
    requirements: { _method: post }

pointage_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DeclareNounouGestNounouBundle:Pointage:edit" }
    requirements: { _method: get }

pointage_update:
    pattern:  /{id}/update
    defaults: { _controller: "DeclareNounouGestNounouBundle:Pointage:update" }
    requirements: { _method: post|put }

pointage_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DeclareNounouGestNounouBundle:Pointage:delete" }
    requirements: { _method: post|delete }
